### ISSUE TITLE
[Bug] ChatQnA model is hallucinating

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#1026] opened 2024-10-24 23:20 UTC
### Priority

Undecided

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest`

### Description

Deployed ChatQnA on AWS cloud, the model is hallucinating, see the response 

<img width="1585" alt="image" src="https://github.com/user-attachments/assets/f29ac243-2479-415f-b42e-443914147670">

### Reproduce steps

https://opea-project.github.io/latest/getting-started/README.html

**Comment by arun-gupta** [comment] 2024-10-25 01:14
This may be related to https://github.com/opea-project/GenAIExamples/issues/1005

**Comment by daniel-de-leon-user293** [comment] 2024-10-25 20:42
Hi @arun-gupta!

By any chance, did you also provide input data for the RAG vector database that includes information about OPEA (e.g. the OPEA main README on github)?
![image](https://github.com/user-attachments/assets/8d4e57dc-501d-4d14-aa47-94577fb2a615)

LLM hallucination is usually observed with respect to its training and input data (for RAG). The default model for this example is [`Intel/neural-chat-7b-v3-3`](https://huggingface.co/Intel/neural-chat-7b-v3-3) which wouldn't have had any info of OPEA in its training data given that it was released almost a year ago and OPEA is only ~6 months old. Thus, if no `raw data source` is provided in conjunction with the input query `what is opea?`, then, it is my understanding that we should expect the model to return a nonsensical/incorrect response.

**Comment by arun-gupta** [comment] 2024-10-28 02:05
The first response in the image is before providing the link, the second response is after providing the link to https://opea.dev.

**Comment by XinyaoWa** [comment] 2024-10-29 03:31
Hi, I have tried to reproduce the issue,  but I get the correct result both with build-from-source images and images pulled from docker hub. Would you please try to build the image from the latest code and test again? We will also update the images in docker hub soon.
![image (5)](https://github.com/user-attachments/assets/76bcea4f-5067-46db-9f18-2301c927223c)

**Comment by Spycsh** [comment] 2024-10-31 08:03
Normally this issue is caused by the OpenAI format parameters such as `frequency_penalty` and `presence_penalty` (Xeon/Gaudi), which may lead to an accuracy problem on TGI. This should be fixed after https://github.com/opea-project/GenAIExamples/pull/974. The latest Docker image is https://hub.docker.com/r/opea/chatqna which is built 3 days ago so now I think it should work fine with a latest build.

**Comment by daniel-de-leon-user293** [comment] 2024-11-01 23:50
I pulled the images from docker hub on Xeon and I was unable to reproduce the output XinayoWa is getting when providing https://opea.dev/. As you can see from the screen shot below, it incorrectly defines the OPEA acronym. It seems to take an "educated guess" given that the acronym is actually never defined in that provided link. It also fails to mention anything about AI which is included in the webpage.
 
In my third question, I removed that initial link from the vector DB and added a more informational link (https://opea-project.github.io/latest/introduction/index.html) where the OPEA acronym is defined. We see a much better answer that provides more relevant information of OPEA. 
 
We're currently exploring a hallucination guardrail microservice that could prevent the service from outputting these "educated guesses" in the second question. 

![image](https://github.com/user-attachments/assets/a4b927da-4690-4edc-8f7a-cc16d9362c6f)

**Comment by joshuayao** [comment] 2024-12-06 04:44
Hi @arun-gupta, could we close this issue?

**Comment by joshuayao** [comment] 2024-12-13 02:45
Closed due to no updates in the past 40 days.

**Closed by joshuayao** 2024-12-13 02:45 UTC
Labels: bug, Dev
