### ISSUE TITLE
GenAIExample for ChatQnA Xeon not working - error in the microservice chaqna-xeon-backend-server

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#251] opened 2024-06-01 01:58 UTC
Following instructions in the readme - https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md

After the docker compose up command, I am checking the logs of the different microservices. The log for the microservice chaqna-xeon-backend-server is throwing errors and exception. How to solve the problem and fix the issue? The error is below.

/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
[2024-06-01 01:47:23,254] [    INFO] - CORS is enabled.
[2024-06-01 01:47:23,254] [    INFO] - Setting up HTTP server
[2024-06-01 01:47:23,254] [    INFO] - Uvicorn server setup on port 8888
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)
[2024-06-01 01:47:23,265] [    INFO] - HTTP server setup successful
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 400, in request
    self.endheaders()
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1058, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 996, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 238, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x704b2c33c550>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='3.17.179.238', port=6000): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x704b2c33c550>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/chatqna.py", line 75, in <module>
    asyncio.run(chatqna.schedule())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/user/chatqna.py", line 67, in schedule
    await self.megaservice.schedule(initial_inputs={"text": "What is the revenue of Nike in 2023?"})
  File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 45, in schedule
    response = await self.execute(node, inputs, llm_parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/GenAIComps/comps/cores/mega/orchestrator.py", line 76, in execute
    response = requests.post(url=endpoint, data=json.dumps(inputs), proxies={"http": None})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='3.17.179.238', port=6000): Max retries exceeded with url: /v1/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x704b2c33c550>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by mandalrajiv** [comment] 2024-06-05 12:40
@huiyan2021 - Thanks for looking into this. I was testing this on an AWS EC2 instance. Please let me know if you have any questions for me or need additional details.

**Comment by huiyan2021** [comment] 2024-06-06 01:19
Hi @mandalrajiv, I will try to see I can reproduce on AWS. 

From the error log, it seems that /v1/embeddings can not be connected. Did you validate embedding service seperately?
```
curl http://${host_ip}:6000/v1/embeddings \
  -X POST \
  -d '{"text":"hello"}' \
  -H 'Content-Type: application/json'
```

**Comment by moting9** [comment] 2024-06-06 06:19
@huiyan2021  Hello, huiyan, I'm not sure whether my issue is the same one, my setup is local xeon, not aws, But  embedding service failed to work, I made sure I created  my token with "write" right. 

Should we have no proxy setting during docker image build?

_6df137efc718   opea/embedding-tei:latest                               "python embedding_te…"   8 minutes ago   Up 8 minutes   0.0.0.0:6000->6000/tcp, :::6000->6000/tcp                                              embedding-tei-server_
e47f482d1237   ghcr.io/huggingface/text-embeddings-inference:cpu-1.2   "text-embeddings-rou…"   13 minutes ago   Up 13 minutes   0.0.0.0:6006->80/tcp, :::6006->80/tcp                                                  tei-embedding-server_

 docker logs  6df137efc718
_/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:149: UserWarning: Field "model_name_or_path" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
[2024-06-06 05:59:31,212] [    INFO] - CORS is enabled.
[2024-06-06 05:59:31,213] [    INFO] - Setting up HTTP server
[2024-06-06 05:59:31,213] [    INFO] - Uvicorn server setup on port 6000
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:6000 (Press CTRL+C to quit)
[2024-06-06 05:59:31,221] [    INFO] - HTTP server setup successful
TEI Gaudi Embedding initialized.
INFO:     10.239.241.147:57112 - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://10.239.241.147:6006/**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/user/.local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/user/.local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 399, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/langsmith/run_helpers.py", line 395, in wrapper
    function_result = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/comps/embeddings/langchain/embedding_tei_gaudi.py", line 23, in embedding
    embed_vector = embeddings.embed_query(input.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/embeddings/huggingface_hub.py", line 109, in embed_query
    response = self.embed_documents([text])[0]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/embeddings/huggingface_hub.py", line 95, in embed_documents
    responses = self.client.post(
                ^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/huggingface_hub/inference/_client.py", line 273, in post
    hf_raise_for_status(response)
  File "/home/user/.local/lib/python3.11/site-packages/huggingface_hub/utils/_errors.py", line 367, in hf_raise_for_status
    raise HfHubHTTPError(message, response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError:

403 Forbidden: None.
**Cannot access content at: http://10.239.241.147:6006/.**
If you are trying to create or update content,make sure you have a token with the `write` role._



docker logs e47f482d1237
_2024-06-06T05:59:29.108115Z  INFO text_embeddings_router: router/src/main.rs:140: Args { model_id: "BAA*/***-****-**-v1.5", revision: None, tokenization_workers: None, dtype: None, pooling: None, max_concurrent_requests: 512, max_batch_tokens: 16384, max_batch_requests: None, max_client_batch_size: 32, auto_truncate: false, hf_api_token: None, hostname: "e47f482d1237", port: 80, uds_path: "/tmp/text-embeddings-inference-server", huggingface_hub_cache: Some("/data"), payload_limit: 2000000, api_key: None, json_output: false, otlp_endpoint: None, cors_allow_origin: None }
2024-06-06T05:59:29.108227Z  INFO hf_hub: /usr/local/cargo/git/checkouts/hf-hub-1aadb4c6e2cbe1ba/b167f69/src/lib.rs:55: Token file not found "/root/.cache/huggingface/token"
2024-06-06T05:59:29.150359Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:20: Starting download
2024-06-06T05:59:29.150393Z  INFO download_artifacts: text_embeddings_core::download: core/src/download.rs:37: Model artifacts downloaded in 36.011µs
2024-06-06T05:59:29.160987Z  INFO text_embeddings_router: router/src/lib.rs:169: Maximum number of tokens per request: 512
2024-06-06T05:59:29.166819Z  INFO text_embeddings_core::tokenization: core/src/tokenization.rs:23: Starting 128 tokenization workers
2024-06-06T05:59:29.420270Z  INFO text_embeddings_router: router/src/lib.rs:194: Starting model backend
2024-06-06T05:59:29.420736Z  INFO text_embeddings_backend_candle: backends/candle/src/lib.rs:124: Starting Bert model on Cpu
2024-06-06T05:59:29.792021Z  WARN text_embeddings_router: router/src/lib.rs:211: Backend does not support a batch size > 4
2024-06-06T05:59:29.792043Z  WARN text_embeddings_router: router/src/lib.rs:212: forcing `max_batch_requests=4`
2024-06-06T05:59:29.792182Z  WARN text_embeddings_router: router/src/lib.rs:263: Invalid hostname, defaulting to 0.0.0.0
2024-06-06T05:59:29.793545Z  INFO text_embeddings_router::http::server: router/src/http/server.rs:1555: Starting HTTP server: 0.0.0.0:80
2024-06-06T05:59:29.793560Z  INFO text_embeddings_router::http::server: router/src/http/server.rs:1556: Ready
2024-06-06T06:00:28.003168Z  INFO embed{total_time="12.541343ms" tokenization_time="985.635µs" queue_time="1.112888ms" inference_time="10.006077ms"}: text_embeddings_router::http::server: router/src/http/server.rs:590: Success_

lsof -i:6006
 _COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 54410 root    4u  IPv4 121171      0t0  TCP *:6006 (LISTEN)
docker-pr 54430 root    4u  IPv6  97470      0t0  TCP *:6006 (LISTEN)_

**Comment by moting9** [comment] 2024-06-06 06:40
@huiyan2021  seem there is access issue for "embedding-tei-server" container to access "embedding-tei-server" container  when http_proxy/https_proxy are set.  during docker image build,  maybe we need to pass no_proxy setting.  

Access from my local console is OK
=======================
_(opea) [root@localhost xeon]# wget http://10.239.241.147:6006/
--2024-06-05 23:28:38--  http://10.239.241.147:6006/
Connecting to 10.239.241.147:6006... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
Saving to: ‘index.html.1’

index.html.1                                [ <=>                                                                         ]       0  --.-KB/s    in 0s

2024-06-05 23:28:38 (0.00 B/s) - ‘index.html.1’ saved [0/0]_

enter  embedding-tei-server
===================
# docker  exec -it -t 6df137efc718  /bin/bash
user@6df137efc718:~/comps/embeddings/langchain$  wget http://10.239.241.147:6006/
--2024-06-06 06:28:55--  http://10.239.241.147:6006/
Resolving proxy
Connecting to proxy... connected.
Proxy request sent, awaiting response... 403 Forbidden
2024-06-06 06:28:55 ERROR 403: Forbidden.

user@6df137efc718:~/comps/embeddings/langchain$ env | grep -ie proxy
https_proxy=http://xxx
http_proxy=http://xxx
user@6df137efc718:~/comps/embeddings/langchain$ unset http_proxy
user@6df137efc718:~/comps/embeddings/langchain$ unset https_proxy
user@6df137efc718:~/comps/embeddings/langchain$ wget http://10.239.241.147:6006/
--2024-06-06 06:29:17--  http://10.239.241.147:6006/
Connecting to 10.239.241.147:6006... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
index.html: Permission denied

Cannot write to ‘index.html’ (Permission denied).

I assume write failure is due to  user has no write right to current dir inside docker, irrelevant with this issue. 


 docker  exec -it -t 6df137efc718  /bin/bash
user@6df137efc718:~/comps/embeddings/langchain$  wget http://10.239.241.147:6006/
--2024-06-06 06:28:55--  http://10.239.241.147:6006/
Resolving proxy.ims.intel.com (proxy.ims.intel.com)... 10.102.248.16
Connecting to proxy.ims.intel.com (proxy.ims.intel.com)|10.102.248.16|:911... connected.
Proxy request sent, awaiting response... 403 Forbidden
2024-06-06 06:28:55 ERROR 403: Forbidden.

user@6df137efc718:~/comps/embeddings/langchain$ env | grep -ie proxy
https_proxy=http://proxy.ims.intel.com:911
http_proxy=http://proxy.ims.intel.com:911
user@6df137efc718:~/comps/embeddings/langchain$ unset http_proxy
user@6df137efc718:~/comps/embeddings/langchain$ unset https_proxy
user@6df137efc718:~/comps/embeddings/langchain$ wget http://10.239.241.147:6006/
--2024-06-06 06:29:17--  http://10.239.241.147:6006/
Connecting to 10.239.241.147:6006... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0
index.html: Permission denied

Cannot write to ‘index.html’ (Permission denied).

**Comment by huiyan2021** [comment] 2024-06-06 09:43
Hi @mandalrajiv, please try following steps and see if works for you:
1. `docker compose -f docker_compose.yaml down`
2. `export no_proxy=3.17.179.238` (I saw this ip from your error log)
3. modify docker_compose.yaml referring to https://github.com/opea-project/GenAIExamples/pull/267/files that @moting9 submitted
4. `docker compose -f docker_compose.yaml up -d`

**Comment by preethivenkatesh** [comment] 2024-06-12 20:45
@moting9 @mandalrajiv  Please let us know if this resolves your issue and we can close it?

**Comment by moting9** [comment] 2024-06-17 02:41
@preethivenkatesh  my issue is resolved. Thanks.

**Closed** 2024-06-18 06:04 UTC
Labels: enhancement, aitce, CPU_XEON
