### ISSUE TITLE
[Bug] MultimodalQnA/docker_compose/intel/cpu/xeon/README.md docker compose typo

### ISSUE THREAD

**Issue by NotAdityaPawar** [opea-project/GenAIExamples#986] opened 2024-10-18 14:35 UTC
### Priority

P4-Low

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

Not sure

### Description

The issue is with the typo for the MultiModalQna readme.md, the docker compose command should be 
`docker-compose -f compose.yaml up -d` instead of the 'docker compose -f compose.yaml up -d'

### Reproduce steps

I tried this command over the aws xeon instance

**Comment by louie-tsai** [comment] 2024-10-21 18:11
@NotAdityaPawar 
the issue should be fixed in the latest main branch.
Let us know any reminding issue.

**Comment by louie-tsai** [comment] 2024-10-28 23:42
@NotAdityaPawar 
Since the issue is fixed in the latest master, we will close the ticket for now.

**Closed by louie-tsai** 2024-10-28 23:42 UTC
