### ISSUE TITLE
ChatQnA Gaudi Script fails if rerun

### ISSUE THREAD

**Issue by mandalrajiv** [opea-project/GenAIExamples#228] opened 2024-05-30 17:37 UTC
The gaudi script for the chatqna example fails if it is executed again after it once executes and fails and needs troubleshooting. Main reason for the failure is the folders already present from prior git clone command The changes help to rerun the script even if git clone folders are present. Also, users who do not have Anaconda installed have the script fail in the miniforge directory lines within the script. Also, added instructions for passing the IP_Address and Hugging Face token as part of running the script command

**Comment by srinarayan-srikanthan** [comment] 2024-06-03 18:25
@mandalrajiv Can you please review the comments in the [PR](https://github.com/opea-project/GenAIExamples/pull/229)

**Comment by mandalrajiv** [comment] 2024-06-05 12:43
@srinarayan-srikanthan - yes, commented on the PR. Rebased and pushed again.

**Comment by yinghu5** [comment] 2024-07-18 01:31
Hi Mandalrajiv, 
 thank you a lot for reporting and fixing the problem. I close the issue. please feel free to to reopen if the problem is still in the new release.

**Closed by yinghu5** 2024-07-18 01:31 UTC
Labels: bug, aitce, Gaudi
