### ISSUE TITLE
The ChatQnA application container does not connect to the backend 

### ISSUE THREAD

**Issue by ShankarRIntel** [opea-project/GenAIExamples#529] opened 2024-08-06 02:21 UTC
After following the instructions end-to-end for the ChatQnA application on Xeon, the UI container does not connect to the backend.

**Comment by ZailiWang** [comment] 2024-08-07 00:08
Hi @ShankarRIntel would you elaborate more about the test command?

**Comment by ShankarRIntel** [comment] 2024-08-07 14:50
I went through all the steps in
GenAIExamples/ChatQnA/docker/xeon/README.md at main · opea-project/GenAIExamples (github.com)<https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker/xeon/README.md>

The services do come up if I use any address  other than localhost ( 127.0.0.1) .  This needs to be mentioned.
But after the services came up.  The chatQnA ui doesn’t seem to work
***@***.***

**Comment by ZailiWang** [comment] 2024-08-12 02:56
Hi @ShankarRIntel In the readme file we provide several options, and in some commands you need to replace the placeholders with the actual values in your env. Would you double check about it, and if the failure is still reproduceable, provide your exact command list so I can help find what is wrong?

**Comment by ZailiWang** [comment] 2024-09-04 09:00
Closing the issue since no update for a while. Feel free to re-open if the issue is still the case.

**Comment by ShankarRIntel** [comment] 2024-09-04 17:41
I have provided the original set of commands run.  I can provide it again.  Please keep this issue open as we are still facing it
________________________________

**Comment by ZailiWang** [comment] 2024-10-17 00:06
Closing the issue since no update for a while. Feel free to re-open if the issue is still the case.

**Closed by ZailiWang** 2024-10-17 00:06 UTC
