### ISSUE TITLE
[Bug] Conversational UI instructions are incomplete and does not work

### ISSUE THREAD

**Issue by arun-gupta** [opea-project/GenAIExamples#990] opened 2024-10-18 23:30 UTC
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [ ] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [ ] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

`latest`

### Description

Deployed ChatQnA example in IBM Cloud and trying to configure Conversational UI. The Compose file does not start up and gives the following error:

```
ubuntu@opea-demo:~/GenAIExamples/ChatQnA/docker_compose/intel/cpu/xeon$ docker compose up -d
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "BACKEND_SERVICE_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATAPREP_SERVICE_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "no_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "https_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "http_proxy" variable is not set. Defaulting to a blank string. 
WARN[0000] The "LOGFLAG" variable is not set. Defaulting to a blank string. 
service "chatqna-xeon-nginx-server" depends on undefined service "chatqna-xeon-ui-server": invalid compose project
```

Seems like there are more steps required to configure this.

### Reproduce steps

Follow the steps here to deploy anywhere https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA

**Comment by ZailiWang** [comment] 2024-10-23 02:51
Hi Arun, in the doc there are [parts](https://github.com/opea-project/GenAIExamples/tree/main/ChatQnA#quick-start-1setup-environment-variable) for aiding environment variable setup. Not sure if it is missed or the settings are not taking effect.

**Comment by arun-gupta** [comment] 2024-10-23 04:28
Error message is complaining:

```
WARN[0000] The "BACKEND_SERVICE_ENDPOINT" variable is not set. Defaulting to a blank string. 
WARN[0000] The "DATAPREP_SERVICE_ENDPOINT" variable is not set. Defaulting to a blank string. 
```

`set_env.sh` at https://github.com/opea-project/GenAIExamples/blob/main/ChatQnA/docker_compose/intel/cpu/xeon/set_env.sh does not have those environment variables defined. It only has:

```
export EMBEDDING_MODEL_ID="BAAI/bge-base-en-v1.5"
export RERANK_MODEL_ID="BAAI/bge-reranker-base"
export LLM_MODEL_ID="Intel/neural-chat-7b-v3-3"
export INDEX_NAME="rag-redis"
```

**Comment by ZailiWang** [comment] 2024-10-23 08:35
Hi Arun, there was [an env variable update PR](https://github.com/opea-project/GenAIExamples/pull/977) merged a few days ago, in which the variable is [not needed in the yaml file](https://github.com/opea-project/GenAIExamples/pull/977/files#diff-8ca2a93bf66f5e5b2ef802f09f2df566492be9371e70905f79e52ab4cd5d497aL128). Would you try again with latest commit?

**Comment by ZailiWang** [comment] 2024-11-18 01:44
Closing the issue since no update for a while. Arun, please re-open it if the issue is still reproduced with latest commit, thanks.

**Closed by ZailiWang** 2024-11-18 01:44 UTC
Labels: bug, aitce
