### ISSUE TITLE
Delete file is fault by http://${host_ip}:6009/v1/dataprep/delete_file"

### ISSUE THREAD

**Issue by NeoZhangJianyu** [opea-project/GenAIExamples#539] opened 2024-08-07 06:26 UTC
I test the ChatQnA example.
After add knowledge base by:
```
curl -X POST "http://${host_ip}:6007/v1/dataprep" \
     -H "Content-Type: multipart/form-data" \
     -F "files=@./nke-10k-2023.pdf"
or
curl -X POST "http://${host_ip}:6007/v1/dataprep" \
     -H "Content-Type: multipart/form-data" \
     -F 'link_list=["https://opea.dev"]'
```

I try to delete single file by cmd:
```
curl -X POST "http://${host_ip}:6009/v1/dataprep/delete_file" \
     -d '{"file_path": "https://opea.dev"}' \
     -H "Content-Type: application/json"
or
curl -X POST "http://${host_ip}:6009/v1/dataprep/delete_file" \
     -d '{"file_path": "nke-10k-2023.pdf"}' \
     -H "Content-Type: application/json"
```

The file or link is present when check by:
```
curl -X POST "http://${host_ip}:6008/v1/dataprep/get_file" \
     -H "Content-Type: application/json"
```

But when delete all files by:
```
curl -X POST "http://${host_ip}:6009/v1/dataprep/delete_file" \
     -d '{"file_path": "all"}' \
     -H "Content-Type: application/json"
```
It works well.

**Comment by letonghan** [comment] 2024-08-13 02:10
Hi @NeoZhangJianyu , your issue is caused by the fail of uploading file. Root cause is the missing of a dataprep parameter.
This issue was already fixed by [this PR](https://github.com/opea-project/GenAIExamples/pull/545) and the issue will be closed.

**Closed by letonghan** 2024-08-13 02:10 UTC
